
INSERT INTO bank (bank_id,DATE_OUVERTURE,ADRESS) values(1,CURRENT_TIMESTAMP(),'PARIS');
INSERT INTO CUSTOMER (CUSTOMER_id,FIRSTNAME, LASTNAME,bank_id) VALUES (1,'GUETET', 'NABIL',1);
INSERT INTO Account (account_id,NUM_ACCOUNT, ACCOUNT_TYPE, balance,CUSTOMER_ID) VALUES (1,'FR11111111111', 'courant', '100000',1);
INSERT INTO Account (account_id,NUM_ACCOUNT, ACCOUNT_TYPE, balance,CUSTOMER_ID) VALUES (2,'FR22222222222', 'courant', '182200',1);
  
 INSERT INTO TRANSACTION (TRANSACTION_ID,DATE_TRANSACTION,account_id,etat,TYPE_TRANSACTION) VALUES (1,CURRENT_TIMESTAMP(),1,1L,1L);
 INSERT INTO TRANSACTION (TRANSACTION_ID,DATE_TRANSACTION,account_id,etat,TYPE_TRANSACTION) VALUES (2,CURRENT_TIMESTAMP(),1,2L,2L);
 INSERT INTO TRANSACTION (TRANSACTION_ID,DATE_TRANSACTION,account_id,etat,TYPE_TRANSACTION) VALUES (3,CURRENT_TIMESTAMP(),1,2L,3L);
 INSERT INTO TRANSACTION (TRANSACTION_ID,DATE_TRANSACTION,account_id,etat,TYPE_TRANSACTION) VALUES (4,CURRENT_TIMESTAMP(),2,0L,4L);

